# Generated by Django 3.1.14 on 2022-07-14 06:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holding',
            name='stockSymbol',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='league',
            name='endTime',
            field=models.DateField(default=datetime.datetime(2022, 7, 14, 6, 35, 45, 308301)),
        ),
        migrations.AlterField(
            model_name='league',
            name='entryFee',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='league',
            name='prizePool',
            field=models.IntegerField(default=1000),
        ),
        migrations.AlterField(
            model_name='league',
            name='startTime',
            field=models.DateField(default=datetime.datetime(2022, 7, 14, 6, 35, 45, 308286)),
        ),
        migrations.AlterField(
            model_name='league',
            name='totalSpots',
            field=models.IntegerField(default=100),
        ),
    ]
